# Generated by Django 3.1 on 2020-08-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full TIme', 'Full TIme'), ('Part Time', 'Part TIme')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
